/** Declaration file generated by dts-gen */

export const functional: boolean

export const props: {
  code: {
    type: any
  }
  language: {
    default: string
    type: any
  }
}

export function render(h: any, ctx: any): any

export namespace render {
  const prototype: {}
}
